[build]
  base = "rb-gestao"
  publish = "rb-gestao"
  functions = "rb-gestao/netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
